import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";
import { copyFileSync, mkdirSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];

if (!["dev", "beta", "production"].includes(mode)) {
	throw new Error(`Invalid mode: ${mode}`);
}

console.log(`Building in ${mode} mode`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/styles.scss", "src/main.ts"],
	bundle: true,
	minify: mode === "production",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: mode === "dev" ? "inline" : false,
	treeShaking: true,
	outdir: "dist",
	plugins: [sassPlugin()],
});

if (mode === "dev") {
	// In dev mode, do an initial build first to ensure dist exists
	await context.rebuild();
	// Copy manifest.json to dist folder (cross-platform)
	try {
		mkdirSync("dist", { recursive: true });
		copyFileSync("manifest.json", join("dist", "manifest.json"));
		console.log("✓ Copied manifest.json to dist/");
	} catch (error) {
		console.error("✗ Failed to copy manifest.json:", error.message);
		process.exit(1);
	}
	// Then start watch mode
	await context.watch();
} else {
	await context.rebuild();
	// Copy manifest.json to dist folder (cross-platform)
	try {
		mkdirSync("dist", { recursive: true });
		copyFileSync("manifest.json", join("dist", "manifest.json"));
		console.log("✓ Copied manifest.json to dist/");
	} catch (error) {
		console.error("✗ Failed to copy manifest.json:", error.message);
		process.exit(1);
	}
	process.exit(0);
}
